# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   test:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: checkout
#       uses: actions/checkout@master
    
#     - name: gradle test
#       uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
#       with:
#         args: test
        
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@master
    
#     - name: gradle jar
#       uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
#       with:
#         args: jar
        
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: chigirh/com-chigirh-tools-jar
        path: tools-jar
      
#     - name: Setup git repogitories
#       env:
#         SECRET_DEPLOY_KEY: ${{ secrets.SECRET_DEPLOY_KEY }}
#       run: |
#         mkdir ~/.ssh
#         echo ${{ secrets.SECRET_DEPLOY_KEY }} > ~/.ssh/id_rsa.pem
#         chmod 600 ~/.ssh/id_rsa.pem
#         ssh -T git@github.com
#         cd tools-jar
#         git config --global user.email "com-chigirh-tools-common@github.io"
#         git config --global user.name "com-chigirh-tools-common"
#         git config remote.origin.url "git@github.comchigirh/com-chigirh-tools-jar.git"
#         git checkout master
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        key: ${{ secrets.SECRET_DEPLOY_KEY }} # 必須
        name: id_rsa # 省略可
        known_hosts: ${{ secrets.KNOWN_HOSTS }} # 必須

#     - name: Build pages
#       run: |
#         ls
#         cp -f ./libs/sample.txt ./tools-jar/sample.txt

    - name: Deploy pages
      env:
        GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
      run: |
        cp -f ./libs/sample.txt ./tools-jar/sample.txt
        cd tools-jar
        git status
        git add .
        git commit -m "Deploy $GITHUB_SHA by GitHub Actions"
        git push origin master
    
#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.SECRET_KEY }}
#         repository: chigirh/com-chigirh-tools-jar
#         branch: master

    
